FROM httpd:2.4
COPY containers/apache/httpd.conf /usr/local/apache2/conf/httpd.conf

# Build sample
# docker build -t apache -f containers/apache/Dockerfile .

# Run sample
# docker run -it --rm apache sh
