apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
spec:
  replicas: {{ .Values.containers.apache.replicas }}
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
        - name: apache
          image: "{{ .Values.containers.apache.repository }}:{{ .Values.containers.apache.tag }}"
          ports:
            - containerPort: 80
