name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push PHP Docker Image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: ./
          file: ./containers/php/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/app-php:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and Push PHP Docker Image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: ./
          file: ./containers/apache/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/app-apache:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
